require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'script/**/*'
    - 'bin/**/*'
    - 'client/**/*'
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Exclude:
    - 'db/seeds.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
Metrics/MethodLength:
  Max: 25
