require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 25
